# Generated by Django 3.0.5 on 2020-08-28 08:12

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CricketPlayer',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('player_image', models.ImageField(upload_to='players')),
                ('jersey_number', models.PositiveIntegerField(unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CricketTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_identifier', models.CharField(max_length=10, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.ImageField(upload_to='team_logo')),
                ('club_state', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchesFixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playing_team1', models.CharField(max_length=100)),
                ('playing_team2', models.CharField(max_length=100)),
                ('playing_team1_logo', models.ImageField(upload_to='')),
                ('playing_team2_logo', models.ImageField(upload_to='')),
                ('match_venue', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('match_winner', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchVenues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.CharField(max_length=100)),
                ('stadium_city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MatchVenues',
                'verbose_name_plural': 'MatchVenues',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('matches_won', models.PositiveIntegerField(default=0)),
                ('matches_lost', models.PositiveIntegerField(default=0)),
                ('matches_tied', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Points',
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField()),
                ('total_runs', models.PositiveIntegerField()),
                ('highest_score', models.PositiveIntegerField()),
                ('fifties', models.PositiveIntegerField()),
                ('hundreds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricket_application.CricketPlayer')),
            ],
            options={
                'verbose_name': 'PlayerHistory',
                'verbose_name_plural': 'PlayerHistory',
            },
        ),
        migrations.AddField(
            model_name='cricketplayer',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_application.CricketTeam'),
        ),
    ]
